variables:
- group: "production_v2"

trigger:
  branches:
    include:
    - v2

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI
  steps:
  - powershell: |
      npm ci
      npm run build --if-present
    displayName: "Install and build"
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/_site"
      includeRootFolder: false
      archiveFile: "$(System.ArtifactStagingDirectory)/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.ArtifactStagingDirectory)/build$(Build.BuildId).zip'
      artifactName: 'site'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/v2'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: ExtractFiles@1
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/site/*.zip'
            destinationFolder: '$(Pipeline.Workspace)/wip'
            cleanDestinationFolder: true
            overwriteExistingFiles: true
        - powershell: |
            Set-Location $(Pipeline.Workspace)/wip
            Rename-Item -Path .htaccess.sample -NewName .htaccess
          displayName: "Prepare files"
        - task: CopyFilesOverSSH@0
          inputs:
            sshEndpoint: '$(sshEndpoint)'
            sourceFolder: '$(Pipeline.Workspace)/wip'
            contents: '**'
            targetFolder: '$(sshTargetFolder)'
            readyTimeout: '20000'
            overwrite: true
